language: python
python:
    # 2.7.9 or greater needed for 'cafile=' option in urllib2.urlopen()
    - "2.7.10"

branches:
    only:
        - master

sudo: false

matrix:
  fast_finish: true

git:
    submodules: false

addons:
  apt:
    packages:
        - python-selinux

install:
    - pip install Pylint==1.5.5 Pep8==1.6.2 Sphinx==1.2.2
    - pip install Autotest==0.16.2
    - pip install inspektor==0.2.0
    - pip install unittest2==0.8.0
    # Necessary so we can 'import selinux'. Although Travis provides a
    # system_site_packages mechanism for this purpose, it blows up
    # with python 2.7.10.
    - export PYTHONPATH="$PYTHONPATH:/usr/lib/python2.7/dist-packages"

script:
    - SPHINXOPTS="-W" make
    - ./run_checkdocs.py
    - ./run_unittests.sh
    - ./run_pylint.sh --FF
    - inspekt style --disable E501,E265,W601,E402,E731,E221

# TODO: Do we need notifications?
#notifications:
#  irc:
#    channels: "irc.oftc.net#autotest"
#    template:
#      - "%{repository}@%{branch}: %{message} (%{build_url})"
