language: python
python:
    - "2.7"

branches:
    only:
        - master

matrix:
  fast_finish: true

git:
    submodules: false

virtualenv:
    system_site_packages: true

before_script:
    - echo "deb http://ppa.launchpad.net/lmr/autotest/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -q
    - sudo apt-get -y --force-yes install autotest

install:
    - pip install Pylint Pep8 Sphinx

script:
    - SPHINXOPTS="-W" make
    - ./run_checkdocs.py
    - ./run_unittests.sh
    - ./run_pylint.sh

# TODO: Do we need notifications?
#notifications:
#  irc:
#    channels: "irc.oftc.net#autotest"
#    template:
#      - "%{repository}@%{branch}: %{message} (%{build_url})"
